// <auto-generated />
using CodeFirstPractice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstPractice.Migrations
{
    [DbContext(typeof(ShelvesContext))]
    [Migration("20200927040559_ThirdMigration")]
    partial class ThirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstPractice.Models.ShelfMaterials", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnName("material_name")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(30)
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("ShelfMaterial");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MaterialName = "Birch"
                        },
                        new
                        {
                            ID = 2,
                            MaterialName = "Pine"
                        },
                        new
                        {
                            ID = 3,
                            MaterialName = "Aspen"
                        },
                        new
                        {
                            ID = 4,
                            MaterialName = "Cherry"
                        },
                        new
                        {
                            ID = 5,
                            MaterialName = "Mahogany"
                        },
                        new
                        {
                            ID = 6,
                            MaterialName = "Endangered Species"
                        });
                });

            modelBuilder.Entity("CodeFirstPractice.Models.Shelves", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ShelfMaterialID")
                        .HasColumnName("shelf_materials_id")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("ShelfMaterialID")
                        .HasName("FK_Shelves_ShelfMaterials");

                    b.ToTable("Shelves");

                    b.HasData(
                        new
                        {
                            ID = 3,
                            Name = "Mista Shelf",
                            ShelfMaterialID = 1
                        },
                        new
                        {
                            ID = 4,
                            Name = "Golden Shelf",
                            ShelfMaterialID = 2
                        },
                        new
                        {
                            ID = 5,
                            Name = "Painful Shelf",
                            ShelfMaterialID = 3
                        },
                        new
                        {
                            ID = 6,
                            Name = "Mr. Shelf",
                            ShelfMaterialID = 4
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mr. Shelf",
                            ShelfMaterialID = 5
                        },
                        new
                        {
                            ID = 11,
                            Name = "Mr. Shelf",
                            ShelfMaterialID = 6
                        });
                });

            modelBuilder.Entity("CodeFirstPractice.Models.Shelves", b =>
                {
                    b.HasOne("CodeFirstPractice.Models.ShelfMaterials", "ShelfMaterials")
                        .WithMany("Shelves")
                        .HasForeignKey("ShelfMaterialID")
                        .HasConstraintName("FK_Shelves_ShelfMaterials")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
